# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1luS5_9Pu6kGiqvWUuC30bc8EmGkeCbFt
"""


import streamlit as st
import pickle
import numpy as np

import streamlit as st
import pickle
import numpy as np

# Load the trained model
with open("model.pkl", "rb") as file:
    model = pickle.load(file)

st.title("Salary Prediction App")
st.write("Fill the information below to predict the salary:")

# --- Example Input Fields ---
# You should update these according to your model's input features
experience = st.slider("Years of Experience", 0, 50, 1)


# --- Convert categorical inputs to numerical if needed ---

input_data = np.array([experience])

# Predict and display result
if st.button("Predict Salary"):
    salary = model.predict(input_data)
    st.success(f"Predicted Salary: ₹{salary[0]:,.2f}")
st.title("Salary Prediction App")
st.write("Fill the information below to predict the salary:")

# --- Example Input Fields ---
# You should update these according to your model's input features
experience = st.slider("Years of Experience", 0, 50, 1)



input_data = np.array([[experience]])

# Predict and display result
if st.button("Predict Salary"):
    salary = model.predict(input_data)
    st.success(f"Predicted Salary: ₹{salary[0]:,.2f}")
