# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1luS5_9Pu6kGiqvWUuC30bc8EmGkeCbFt
"""

import streamlit as st
import pickle
import numpy as np

# Load the trained model
with open("model.pkl", "rb") as file:
    model = pickle.load(file)

st.title("Salary Prediction App")
st.write("Fill the information below to predict the salary:")

# --- Input field ---
experience = st.slider("Years of Experience", 0, 50, 1, key="exp_slider")

# --- Prepare input data (2D array) ---
input_data = np.array([[experience]])

# --- Debug info (optional) ---
st.write("Input data shape:", input_data.shape)
st.write("Model expects:", model.n_features_in_, "features")

# --- Predict and display result ---
if st.button("Predict Salary", key="predict_btn"):
    salary = model.predict(input_data)
    st.success(f"Predicted Salary: ₹{salary[0]:,.2f}")
